### ISSUE TITLE
Regions - cannot add custom Lat/Lon

### ISSUE THREAD

**Issue by Scepticalist** [owntracks/android#686]
* **App build number**: .2.1.2(21201)
* **Android version**: 8.0.0   
* **Device**: Samsun S7 Edge

When trying to enter new geofence Region, cannot change the pre-populated lat/lon settings. Only Region name and radius can be highlighted. Using the "next" key on keyboard to move to next field has no effect.

This make it impossilbe to enter a Region unless you're actually at the location you want.

**Comment by binarybucks** [comment]
Can you not select one with the place picker?

**Comment by Scepticalist** [comment]
I might do, if I knew how to.... - there's no mention of how to do it in the online odcumentation that I can find?
I can't do anything with the in-app map except scroll around are you supposed to be able to drop a pin or something there? I tried long presses to try and nothing.

Still remains, I want to put in an exact co-ordinate for the centre of the region.

**Comment by dustin** [comment]
I have an exact lat/lon of something, but the picker only shows a point on a map.  I was attempting to place something in the wilderness where I knew the exact location, but it just showed a solid blue on the map.  Being able to type the position would be significantly easier.

**Comment by binarybucks** [comment]
Fixed with https://github.com/owntracks/android/pull/698

**Comment by liquid-motion** [comment]
This problem is back again in version 2.1.3 (21302) on Android 9.1.0.
